import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "./providers";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wallet",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body  cz-shortcut-listen="true">
        <Providers>
          {children}
        </Providers>
      </body>
=======
      <Providers>
      <body>{children}</body>
      </Providers>
>>>>>>> parent of 3e5d1f2 (Merchant added)
    </html>
  );
}
